In [45]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:

from numpy.random
 for i in range(7):
        arr[i]

IndentationError: unexpected indent (1706112472.py, line 2)

In [5]:
arr

NameError: name 'arr' is not defined

In [11]:
import numpy as np
data1=[1,2,3,4,5,6,7,8,9,0]
arr1 = np.array(data1)


In [12]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [20]:
import numpy as np
data2=[0,9,8,7,6,5,4,3,2,1]
arr2 = np.array(data2)

In [21]:
arr2


array([0, 9, 8, 7, 6, 5, 4, 3, 2, 1])

In [22]:
import numpy as np
data=[0,2,4,6,8]
arr = np.array(data1)

In [23]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [24]:
data + data

[0, 2, 4, 6, 8, 0, 2, 4, 6, 8]

In [25]:
data*2

[0, 2, 4, 6, 8, 0, 2, 4, 6, 8]

In [28]:
arr.dtype

dtype('int32')

In [29]:
arr1.dtype

dtype('int32')

In [30]:
arr2.dtype

dtype('int32')

In [32]:
arr1.shape

(10,)

In [33]:
arr1+arr2

array([ 1, 11, 11, 11, 11, 11, 11, 11, 11,  1])

In [35]:
import numpy as np
data3=[[0,9,8,7,6],[5,4,3,2,1]]
arr3= np.array(data3)

In [36]:
arr3

array([[0, 9, 8, 7, 6],
       [5, 4, 3, 2, 1]])

In [37]:
arr3.shape

(2, 5)

In [38]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [39]:
np.empty((2,2,2))

array([[[4.67296746e-307, 1.69121096e-306],
        [6.23056330e-307, 2.22526399e-307]],

       [[6.23053614e-307, 7.56592338e-307],
        [9.34588061e-307, 9.34531022e-307]]])